Algoritmo NUMMINMAX
	Definir NUMMIN, NUMMAX , NUM , RECORRIDO Como Entero
	
	Escribir "INGRESE EL NUMERO MINIMO"
	LEER NUMMIN
	
	Escribir "INGRESE EL NUMERO MAXIMO"
	Leer NUMMAX
	
	RECORRIDO = 0
	
	Escribir "INGRESE EL NUMERO"
	LEER NUM
	
	MIENTRAS NUM < NUMMAX Y NUM > NUMMIN Hacer
		RECORRIDO = RECORRIDO + 1
		Escribir "INGRESE OTRO NUMERO"
		LEER NUM
	FinMientras
	
	Escribir "LA CANTIDAD DE NUMEROS INGRESADOS ES DE: " RECORRIDO
FinAlgoritmo
